"""School rosters and market metadata for the 2024-2025 season.

The Pac-12 entry reflects the post-realignment reality where Washington State and
Oregon State are the remaining holdouts; Gonzaga is included as an affiliate
because it competes alongside the conference for the simulator's purposes.
"""

SCHOOLS_BY_CONFERENCE = {
    "ACC": [
        "Duke",
        "North Carolina",
        "Virginia",
        "Louisville",
        "NC State",
        "Wake Forest",
        "Miami",
        "Pitt",
        "Syracuse",
        "Boston College",
        "Florida State",
        "Georgia Tech",
        "Notre Dame",
        "Clemson",
        "Virginia Tech",
        "California",
        "Stanford",
        "SMU",
    ],
    "SEC": [
        "LSU",
        "Kentucky",
        "Auburn",
        "Tennessee",
        "Alabama",
        "Florida",
        "Arkansas",
        "Texas A&M",
        "Mississippi State",
        "Ole Miss",
        "Georgia",
        "South Carolina",
        "Vanderbilt",
        "Missouri",
        "Texas",
        "Oklahoma",
    ],
    "Big Ten": [
        "Michigan",
        "Michigan State",
        "Ohio State",
        "Penn State",
        "Wisconsin",
        "Illinois",
        "Indiana",
        "Iowa",
        "Minnesota",
        "Nebraska",
        "Northwestern",
        "Purdue",
        "Maryland",
        "Rutgers",
        "UCLA",
        "USC",
        "Oregon",
        "Washington",
    ],
    "Big 12": [
        "Kansas",
        "Kansas State",
        "Iowa State",
        "Baylor",
        "Texas Tech",
        "TCU",
        "Oklahoma State",
        "West Virginia",
        "Cincinnati",
        "Houston",
        "BYU",
        "UCF",
        "Arizona",
        "Arizona State",
        "Colorado",
        "Utah",
    ],
    "Pac-12": [
        "Washington State",
        "Oregon State",
        "Gonzaga",
    ],
    "Independent": [
        "Chicago State",
        "Hampton",
        "Le Moyne",
        "Lindenwood",
        "Mercyhurst",
        "Queens",
        "Stonehill",
        "Texas Pan American",
    ],
}


BLUE_BLOODS = {"Duke", "Kentucky", "North Carolina", "UCLA", "Kansas"}


MARKET_SIZE = {
    "Duke": 7,
    "North Carolina": 7,
    "Kentucky": 8,
    "Kansas": 7,
    "UCLA": 10,
    "USC": 10,
    "Texas": 9,
    "Florida": 9,
    "LSU": 8,
    "Auburn": 7,
    "Alabama": 7,
    "Tennessee": 7,
    "Arkansas": 6,
    "Michigan": 9,
    "Michigan State": 7,
    "Ohio State": 9,
    "Penn State": 7,
    "Wisconsin": 6,
    "Illinois": 8,
    "Indiana": 6,
    "Iowa": 6,
    "Minnesota": 7,
    "Maryland": 8,
    "Rutgers": 9,
    "Northwestern": 9,
    "Purdue": 6,
    "Oregon": 7,
    "Washington": 8,
    "Kansas State": 5,
    "Iowa State": 5,
    "Baylor": 6,
    "Texas Tech": 6,
    "TCU": 8,
    "Oklahoma State": 5,
    "Oklahoma": 6,
    "West Virginia": 4,
    "Cincinnati": 6,
    "Houston": 9,
    "BYU": 6,
    "UCF": 8,
    "Arizona": 6,
    "Arizona State": 8,
    "Colorado": 7,
    "Utah": 6,
    "Louisville": 6,
    "Virginia": 5,
    "NC State": 5,
    "Wake Forest": 5,
    "Miami": 9,
    "Pitt": 7,
    "Syracuse": 5,
    "Boston College": 9,
    "Florida State": 5,
    "Georgia Tech": 8,
    "Notre Dame": 6,
    "Clemson": 5,
    "Virginia Tech": 5,
    "California": 9,
    "Stanford": 9,
    "SMU": 8,
    "Texas A&M": 7,
    "Mississippi State": 4,
    "Ole Miss": 4,
    "Georgia": 7,
    "South Carolina": 5,
    "Vanderbilt": 7,
    "Missouri": 6,
    "Washington State": 4,
    "Oregon State": 4,
    "Gonzaga": 5,
    "Chicago State": 9,
    "Hampton": 6,
    "Le Moyne": 5,
    "Lindenwood": 5,
    "Mercyhurst": 4,
    "Queens": 6,
    "Stonehill": 5,
    "Texas Pan American": 4,
}


def market_size_score(school: str, program_tier: int) -> int:
    """Return market size score on a 1-10 scale.

    Falls back to a tier-based default for any school not in the lookup.
    """
    if school in MARKET_SIZE:
        return MARKET_SIZE[school]
    tier_default = {1: 8, 2: 7, 3: 5, 4: 4, 5: 3}
    return tier_default.get(program_tier, 4)
